name: ft3
description: FoosTrainer

publish_to: 'none' 

version: 2.0.40+40

environment:
  sdk: ">=2.7.0 <3.0.0"
  # Restrict to prior to 1.22, because of screenshots problem:
  # https://github.com/mmcc007/screenshots/issues/215
  flutter: '>=1.20.0 <1.22.0'

dependencies:
  #audio_service: ^0.14.0
  audio_service:
    path: ../audio_service
  audio_session: ^0.0.6
  build: ^1.3.0
  device_info: '>=0.4.2+7 <2.0.0'
  firebase_analytics: ^5.0.2
  firebase_core: ^0.4.0+9
  flutter:
    sdk: flutter
  torch_compat:
    path: ../flutter_torch_compat
  json_annotation:
  logging: ^0.11.4
  mailto: ^1.0.0
  meta: ^1.1.8
  package_info: '>=0.4.3 <2.0.0'
  permission_handler: ^5.0.1+1
  just_audio: ^0.4.3
  sprintf: ^4.0.2
  url_launcher: ^5.5.3
  wakelock: ^0.1.4+2

dev_dependencies:
  build_config: ^0.4.2
  build_runner: ^1.10.0
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  json_serializable:
  mockito: ^4.1.1
  screenshots: ^2.1.1
  #screenshots:
  #  path: ../screenshots
  test:

#dependency_overrides:
#  process: ^4.0.0-nullsafety.2
#  pl#atform: ^3.0.0-nullsafety.1
#  file: ^6.0.0-nullsafety.1

flutter:
  uses-material-design: true
  assets:
    - assets/
