name: ft3
description: FoosTrainer

publish_to: 'none' 

version: 2.0.46+46

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ^3.13.3

dependencies:
  audio_service: ^0.18.11
  audio_session: ^0.1.16
  build: ^2.4.1
  # charts_flutter: ^0.10.0
  device_info_plus: ^9.0.3
  equatable: ^2.0.5
  expandable: ^5.0.1
  firebase_analytics: ^10.4.5
  firebase_core: ^2.15.1
  #floor: ^1.4.2
  floor: 
    path: ../floor_1.4.2/floor
  flutter:
    sdk: flutter
  #torch_compat:
  #  path: ../flutter_torch_compat
  #in_app_review: ^2.0.2
  infinite_scroll_pagination: ^4.0.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  logging: ^1.2.0
  mailto: ^2.0.0
  meta: ^1.9.1
  package_info_plus: ^4.1.0
  permission_handler: ^10.4.5
  just_audio: ^0.9.34
  rate_my_app: ^2.0.0
  sprintf: ^7.0.0
  # version 6.0.16 causes an error in flutter run:
  # "A problem occurred evaluating project ':url_launcher_android'...
  # Could not find method buildFeatures() ... on extension 'android' of type com.android.build.gradle.LibraryExtension."
  url_launcher: ^6.1.14
  wakelock_plus: ^1.1.1
  collection: ^1.17.2

dev_dependencies:
  build_config: ^1.1.1
  build_runner: ^2.4.6
  floor_generator: #^1.4.2
    path: ../floor_1.4.2/floor_generator
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  json_serializable: ^6.7.1
  mockito: ^5.4.2
  #screenshots: ^2.1.1
  #screenshots:
  #  path: ../screenshots
  test: ^1.24.3

flutter:
  uses-material-design: true
  assets:
    - assets/
