name: ft3
description: FoosTrainer

publish_to: 'none' 

version: 2.0.46+46

environment:
  sdk: '>=2.7.0 <3.0.0'
  flutter: '>=2.0.0 <3.0.0'

dependencies:
  audio_service: ^0.17.1
  audio_session: ^0.1.5
  build: ^2.0.2
  # charts_flutter: ^0.10.0
  device_info: ^2.0.2
  equatable: ^2.0.3
  expandable: ^5.0.1
  firebase_analytics: ^8.1.2
  firebase_core: ^1.3.0
  floor: ^1.1.0
  flutter:
    sdk: flutter
  #torch_compat:
  #  path: ../flutter_torch_compat
  infinite_scroll_pagination: ^3.0.1+1
  intl: ^0.17.0
  json_annotation: ^4.0.1
  logging: ^1.0.1
  mailto: ^2.0.0
  meta: ^1.3.0
  package_info: ^2.0.2
  permission_handler: ^8.1.1
  just_audio: ^0.8.0
  sprintf: ^6.0.0
  url_launcher: ^6.0.7
  wakelock: ^0.5.2

dev_dependencies:
  build_config: ^1.0.0
  build_runner: ^2.0.5
  floor_generator: ^1.1.0
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  json_serializable: ^4.1.3
  mockito: ^5.0.10
  #screenshots: ^2.1.1
  #screenshots:
  #  path: ../screenshots
  test: ^1.16.8

flutter:
  uses-material-design: true
  assets:
    - assets/
