name: ft3
description: FoosTrainer

publish_to: 'none' 

version: 2.0.40+40

environment:
  sdk: '>=2.7.0 <3.0.0'
  flutter: '>=2.0.0 <3.0.0'

dependencies:
  audio_service: ^0.16.2+1
  audio_session: ^0.0.11
  build: ^1.5.2
  device_info: ^2.0.0
  firebase_analytics: ^7.0.1
  firebase_core: ^0.7.0
  flutter:
    sdk: flutter
  torch_compat:
    path: ../flutter_torch_compat
  json_annotation:
  logging: ^1.0.1
  mailto: ^1.0.0
  meta: ^1.1.8
  package_info: ^2.0.0
  permission_handler: ^5.0.1+1
  just_audio: ^0.6.15+1
  sprintf: ^6.0.0
  url_launcher: ^6.0.3
  wakelock: ^0.5.0+2

dev_dependencies:
  build_config: ^0.4.2
  build_runner: ^1.10.0
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  json_serializable: ^3.4.1
  mockito: ^4.1.1
  #screenshots: ^2.1.1
  #screenshots:
  #  path: ../screenshots
  test:

flutter:
  uses-material-design: true
  assets:
    - assets/
