name: ft3
description: FoosTrainer

publish_to: 'none' 

version: 2.0.46+46

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0 <3.0.0'

dependencies:
  audio_service: ^0.18.11
  audio_session: ^0.1.5
  build: ^2.0.2
  # charts_flutter: ^0.10.0
  device_info: ^2.0.2
  equatable: ^2.0.3
  expandable: ^5.0.1
  firebase_analytics: ^10.4.5
  firebase_core: ^2.15.1
  floor: ^1.1.0
  flutter:
    sdk: flutter
  #torch_compat:
  #  path: ../flutter_torch_compat
  #in_app_review: ^2.0.2
  infinite_scroll_pagination: ^4.0.0
  intl: ^0.18.1
  json_annotation: ^4.0.1
  logging: ^1.0.1
  mailto: ^2.0.0
  meta: ^1.3.0
  package_info: ^2.0.2
  permission_handler: ^10.4.3
  just_audio: ^0.9.34
  #rate_my_app: ^2.0.0
  sprintf: ^7.0.0
  # version 6.0.16 causes an error in flutter run:
  # "A problem occurred evaluating project ':url_launcher_android'...
  # Could not find method buildFeatures() ... on extension 'android' of type com.android.build.gradle.LibraryExtension."
  url_launcher: '>=6.0.0 <6.0.16'
  wakelock: ^0.6.2
  collection: ^1.15.0-nullsafety.4

dev_dependencies:
  build_config: ^1.0.0
  build_runner: ^2.0.5
  floor_generator: ^1.1.0
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  json_serializable: ^6.7.1
  mockito: ^5.0.10
  #screenshots: ^2.1.1
  #screenshots:
  #  path: ../screenshots
  test: ^1.16.8

flutter:
  uses-material-design: true
  assets:
    - assets/
