name: ft3
description: FoosTrainer

publish_to: 'none' 

version: 2.0.28+28

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  audio_service: ^0.14.0
  audio_session: ^0.0.6
  build: ^1.3.0
  firebase_analytics: ^5.0.2
  firebase_core: ^0.4.0+9
  flutter:
    sdk: flutter
  json_annotation:
  logging: ^0.11.4
  meta: ^1.1.8
  just_audio: ^0.4.3
  sprintf: ^4.0.2

dev_dependencies:
  build_config: ^0.4.2
  build_runner: ^1.10.0
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  json_serializable:
  mockito: ^4.1.1
  screenshots: ^2.1.1
  test:

flutter:
  uses-material-design: true
  assets:
    - assets/
