# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane


require '../../flutter_utils'

default_platform(:ios)

# Good reference: https://github.com/artsy/eigen/blob/faa02e2746194d8d7c11899474de9c517435eca4/fastlane/Fastfile#L131-L149

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do |options|
    build_app(clean: false)
    release = options[:release]
    version_name = FlutterUtils.version_name
    changelog = read_changelog(
      changelog_path: '../CHANGELOG.md',
      section_identifier: "[#{release}]",
      excluded_markdown_elements: ['-', '###']
    )
    upload_to_testflight(
      beta_app_feedback_email: 'foostrainer@gmail.com',
      changelog: changelog,
    )
  end

  desc "Push a new release build to the App Store"
  lane :prod do
    year = Time.new.year
    upload_to_app_store(
      app_version: FlutterUtils.version_name,
      build_number: FlutterUtils.version.to_s,
      submit_for_review: true,
      skip_binary_upload: true,
      force: false, # Set to true to skip manual verification of preview.
      overwrite_screenshots: true,
      automatic_release: true,
      copyright: "Copyright #{year} The FoosTrainer Authors. All rights reserved.",
      primary_category: 'SPORTS',
      secondary_category: 'HEALTH_AND_FITNESS',
      price_tier: 0, # Free
      app_rating_config_path: 'fastlane/rating_config.json',
      app_review_information: {
        first_name: 'Brian',
        last_name: 'Eaton',
        email_address: 'brian@speakingincode.net',
        demo_user: '',
        demo_password: '',
        notes: 'App should be usable even with no user.',
      },
      submission_information: {
        add_id_info_limits_tracking: true,
        add_id_info_serves_ads: false,
        add_id_info_tracks_action: true,
        add_id_info_tracks_install: true,
        add_id_info_uses_idfa: false,
        content_rights_has_rights: true,
        content_rights_contains_third_party_content: false,
        export_compliance_uses_encryption: false,
        export_compliance_platform: 'ios',
        export_compliance_compliance_required: false,
        export_compliance_encryption_updated: false,
        export_compliance_app_type: nil,
        export_compliance_is_exempt: false,
        export_compliance_contains_third_party_cryptography: false,
        export_compliance_contains_proprietary_cryptography: false,
        export_compliance_available_on_french_store: true,
      }
    )
  end
end
