# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

require 'yaml'
require '../../flutter_utils'

default_platform(:android)

platform :android do
  desc "Test changelog functionality"
  lane :changelog do |options|
    release = options[:release]
    cl = read_changelog(
      changelog_path: '../CHANGELOG.md',
      section_identifier: "[#{release}]",
      excluded_markdown_elements: ['-', '###']
    )
    print cl
  end

  lane :make_changelog do |options|
    release = options[:release]
    FlutterUtils.create_tag(release)
    version = FlutterUtils.version
    changelog = read_changelog(
      changelog_path: '../CHANGELOG.md',
      section_identifier: "[#{release}]",
      excluded_markdown_elements: ['-', '###']
    )
    android_path = 'metadata/android/en-US/changelogs/%d.txt' % version
    File.write(android_path, changelog)
  end

  desc "Increment build version"
  lane :bump_version do
    FlutterUtils.bump_version
  end

  desc "Submit a new beta Build to Google Play Store"
  lane :beta do
    upload_to_play_store(
      aab: '../build/app/outputs/bundle/release/app-release.aab',
      track: 'beta',
      version_code: FlutterUtils.version(),
    )
  end

  desc "Promote beta version to prod"
  lane :prod do
    upload_to_play_store(
      track: 'beta',
      track_promote_to: 'production',
      skip_upload_apk: true,
      skip_upload_aab: true,
      skip_upload_metadata: true,
      skip_upload_changelogs: true,
      skip_upload_screenshots: true,
      skip_upload_images: true,
    )
  end
end
