# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

require 'yaml'
require '../../flutter_utils'

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new beta Build to Google Play Store"
  lane :beta do
    version_code = FlutterUtils.bump_version()
    system('flutter', 'build', 'appbundle', exception: true)
    #gradle(task: "clean assembleRelease")
    upload_to_play_store(
      aab: '../build/app/outputs/bundle/release/app-release.aab',
      track: 'beta',
      version_code: version_code,
    )
  end

  desc "Promote beta version to prod"
  lane :prod do
    upload_to_play_store(version_code: FlutterUtils.version())
  end
end
